# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mni < Formula
  desc "Command line client for mNi Cloud"
  homepage "https://github.com/mNi-Cloud/cli"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mNi-Cloud/cli/releases/download/v1.0.3/mni_Darwin_x86_64.tar.gz"
      sha256 "62e19dfe7e81d49f5e70402bcdd7f19d8a026ec63b2819b136351162481509aa"

      define_method(:install) do
        bin.install "mni"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mNi-Cloud/cli/releases/download/v1.0.3/mni_Darwin_arm64.tar.gz"
      sha256 "677a37ce0ba596ade80a2e6d4c3249e95da16845fd680dbea22c07860c968f40"

      define_method(:install) do
        bin.install "mni"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mNi-Cloud/cli/releases/download/v1.0.3/mni_Linux_x86_64.tar.gz"
      sha256 "18fa0336af36166e7fb56624f732681cb05c24433295b200b54f1cc58da04323"
      define_method(:install) do
        bin.install "mni"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mNi-Cloud/cli/releases/download/v1.0.3/mni_Linux_arm64.tar.gz"
      sha256 "81a7e800ce7c9bae80751d5196907c9bb79ec0f5a752024b28a23e9e4bcc32c6"
      define_method(:install) do
        bin.install "mni"
      end
    end
  end

  test do
    system "#{bin}/mni", "--version"
  end
end
